// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "../ui.h"

void ui_screenhomeairpressure_screen_init(void)
{
ui_screenhomeairpressure = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenhomeairpressure, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_containertopbarairpressure = lv_obj_create(ui_screenhomeairpressure);
lv_obj_remove_style_all(ui_containertopbarairpressure);
lv_obj_set_width( ui_containertopbarairpressure, lv_pct(100));
lv_obj_set_height( ui_containertopbarairpressure, lv_pct(15));
lv_obj_set_x( ui_containertopbarairpressure, lv_pct(0) );
lv_obj_set_y( ui_containertopbarairpressure, lv_pct(-43) );
lv_obj_set_align( ui_containertopbarairpressure, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_containertopbarairpressure,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_containertopbarairpressure, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_containertopbarairpressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_containertopbarairpressure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_green);
ui_object_set_themeable_style_property(ui_containertopbarairpressure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_green);

ui_labeltoptexthome1 = lv_label_create(ui_containertopbarairpressure);
lv_obj_set_width( ui_labeltoptexthome1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltoptexthome1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltoptexthome1, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltoptexthome1,"Smart Box");
ui_object_set_themeable_style_property(ui_labeltoptexthome1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_labeltoptexthome1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_white);
lv_obj_set_style_text_font(ui_labeltoptexthome1, &ui_font_header1Regular, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelairpressuretext = lv_label_create(ui_screenhomeairpressure);
lv_obj_set_width( ui_labelairpressuretext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelairpressuretext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelairpressuretext, lv_pct(1) );
lv_obj_set_y( ui_labelairpressuretext, lv_pct(-15) );
lv_obj_set_align( ui_labelairpressuretext, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelairpressuretext,"Luftdruck");
lv_obj_set_style_text_font(ui_labelairpressuretext, &ui_font_bodyLargeRegular, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_containervalueairpressure = lv_obj_create(ui_screenhomeairpressure);
lv_obj_remove_style_all(ui_containervalueairpressure);
lv_obj_set_width( ui_containervalueairpressure, lv_pct(100));
lv_obj_set_height( ui_containervalueairpressure, lv_pct(20));
lv_obj_set_x( ui_containervalueairpressure, lv_pct(0) );
lv_obj_set_y( ui_containervalueairpressure, lv_pct(3) );
lv_obj_set_align( ui_containervalueairpressure, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_containervalueairpressure,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_containervalueairpressure, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_containervalueairpressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelairpressure = lv_label_create(ui_containervalueairpressure);
lv_obj_set_width( ui_labelairpressure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelairpressure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelairpressure, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelairpressure,"<VALUE>");
ui_object_set_themeable_style_property(ui_labelairpressure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_green);
ui_object_set_themeable_style_property(ui_labelairpressure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_green);
lv_obj_set_style_text_font(ui_labelairpressure, &ui_font_valueLargeRegular, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelunit = lv_label_create(ui_containervalueairpressure);
lv_obj_set_width( ui_labelunit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelunit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelunit, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelunit,"<UNIT>");
ui_object_set_themeable_style_property(ui_labelunit, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_green);
ui_object_set_themeable_style_property(ui_labelunit, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_green);
lv_obj_set_style_text_font(ui_labelunit, &ui_font_bodyNormalRegular, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_containerbottombarairpressure = lv_obj_create(ui_screenhomeairpressure);
lv_obj_remove_style_all(ui_containerbottombarairpressure);
lv_obj_set_width( ui_containerbottombarairpressure, lv_pct(100));
lv_obj_set_height( ui_containerbottombarairpressure, lv_pct(15));
lv_obj_set_x( ui_containerbottombarairpressure, lv_pct(0) );
lv_obj_set_y( ui_containerbottombarairpressure, lv_pct(43) );
lv_obj_set_align( ui_containerbottombarairpressure, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_containerbottombarairpressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_containerbottombarairpressure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_lightgrey);
ui_object_set_themeable_style_property(ui_containerbottombarairpressure, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_lightgrey);

ui_imgconnected1 = lv_img_create(ui_containerbottombarairpressure);
lv_img_set_src(ui_imgconnected1, &ui_img_icons_connected_35x35_png);
lv_obj_set_width( ui_imgconnected1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_imgconnected1, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_imgconnected1, lv_pct(3) );
lv_obj_set_y( ui_imgconnected1, lv_pct(0) );
lv_obj_set_align( ui_imgconnected1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_imgconnected1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgconnected1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labeldatetime1 = lv_label_create(ui_containerbottombarairpressure);
lv_obj_set_width( ui_labeldatetime1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_labeldatetime1, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_labeldatetime1, lv_pct(5) );
lv_obj_set_y( ui_labeldatetime1, lv_pct(0) );
lv_obj_set_align( ui_labeldatetime1, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeldatetime1,"<DD.MM.YY hh:mm>");
lv_obj_set_style_text_align(ui_labeldatetime1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeldatetime1, &ui_font_bodyNormalRegular, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonoptions1 = lv_btn_create(ui_containerbottombarairpressure);
lv_obj_set_width( ui_buttonoptions1, lv_pct(15));
lv_obj_set_height( ui_buttonoptions1, lv_pct(100));
lv_obj_set_align( ui_buttonoptions1, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_buttonoptions1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_buttonoptions1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_buttonoptions1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonoptions1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_buttonoptions1, &ui_img_icons_settings_50x50_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_buttonoptions1, ui_event_buttonoptions1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screenhomeairpressure, ui_event_screenhomeairpressure, LV_EVENT_ALL, NULL);

}
