// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "../ui.h"

void ui_screenrooms_screen_init(void)
{
ui_screenrooms = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenrooms, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labeltitleoptions2 = lv_label_create(ui_screenrooms);
lv_obj_set_width( ui_labeltitleoptions2, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_labeltitleoptions2, LV_SIZE_CONTENT);   /// 4
lv_obj_set_x( ui_labeltitleoptions2, lv_pct(0) );
lv_obj_set_y( ui_labeltitleoptions2, lv_pct(-43) );
lv_obj_set_align( ui_labeltitleoptions2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_labeltitleoptions2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_labeltitleoptions2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_long_mode(ui_labeltitleoptions2,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_labeltitleoptions2,"Räume");
lv_label_set_recolor(ui_labeltitleoptions2,"true");
lv_obj_set_style_text_color(ui_labeltitleoptions2, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltitleoptions2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltitleoptions2, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_containercolorbaroptions1 = lv_obj_create(ui_screenrooms);
lv_obj_remove_style_all(ui_containercolorbaroptions1);
lv_obj_set_width( ui_containercolorbaroptions1, lv_pct(100));
lv_obj_set_height( ui_containercolorbaroptions1, lv_pct(15));
lv_obj_set_x( ui_containercolorbaroptions1, lv_pct(0) );
lv_obj_set_y( ui_containercolorbaroptions1, lv_pct(-43) );
lv_obj_set_align( ui_containercolorbaroptions1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_containercolorbaroptions1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_containercolorbaroptions1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_containercolorbaroptions1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_containercolorbaroptions1, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_containercolorbaroptions1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_containercolorbaroptions1, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN| LV_STATE_DEFAULT);



}
