// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "../ui.h"

void ui_screenfurtheroptions_screen_init(void)
{
ui_screenfurtheroptions = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenfurtheroptions, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_containercolorbaroptions6 = lv_obj_create(ui_screenfurtheroptions);
lv_obj_remove_style_all(ui_containercolorbaroptions6);
lv_obj_set_width( ui_containercolorbaroptions6, lv_pct(100));
lv_obj_set_height( ui_containercolorbaroptions6, lv_pct(15));
lv_obj_set_x( ui_containercolorbaroptions6, lv_pct(0) );
lv_obj_set_y( ui_containercolorbaroptions6, lv_pct(-43) );
lv_obj_set_align( ui_containercolorbaroptions6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_containercolorbaroptions6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_containercolorbaroptions6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_containercolorbaroptions6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_containercolorbaroptions6, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_containercolorbaroptions6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_containercolorbaroptions6, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN| LV_STATE_DEFAULT);



}
