// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#ifndef _UI_COMP_CONTAINERCOLORBANNERBOTTOM1_H
#define _UI_COMP_CONTAINERCOLORBANNERBOTTOM1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT containerColorBannerBottom1
#define UI_COMP_CONTAINERCOLORBANNERBOTTOM1_CONTAINERCOLORBANNERBOTTOM1 0
#define _UI_COMP_CONTAINERCOLORBANNERBOTTOM1_NUM 1
lv_obj_t *ui_containercolorbannerbottom1_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
