// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "../ui.h"


// COMPONENT labelTitleHomeScreen3

lv_obj_t *ui_labeltitlehomescreen3_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_labeltitlehomescreen3;
cui_labeltitlehomescreen3 = lv_label_create(comp_parent);
lv_obj_set_width( cui_labeltitlehomescreen3, lv_pct(100));
lv_obj_set_height( cui_labeltitlehomescreen3, lv_pct(15));
lv_obj_set_x( cui_labeltitlehomescreen3, lv_pct(0) );
lv_obj_set_y( cui_labeltitlehomescreen3, lv_pct(-42) );
lv_obj_set_align( cui_labeltitlehomescreen3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_labeltitlehomescreen3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_labeltitlehomescreen3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(cui_labeltitlehomescreen3,"Smart Box");
lv_obj_set_style_text_align(cui_labeltitlehomescreen3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_labeltitlehomescreen3, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_labeltitlehomescreen3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_green);
ui_object_set_themeable_style_property(cui_labeltitlehomescreen3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_green);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELTITLEHOMESCREEN3_NUM);
children[UI_COMP_LABELTITLEHOMESCREEN3_LABELTITLEHOMESCREEN3] = cui_labeltitlehomescreen3;
lv_obj_add_event_cb(cui_labeltitlehomescreen3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_labeltitlehomescreen3, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_labeltitlehomescreen3_create_hook(cui_labeltitlehomescreen3);
return cui_labeltitlehomescreen3; 
}

