// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "../ui.h"


// COMPONENT labelTitleHomeScreen

lv_obj_t *ui_labeltitlehomescreen_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_labeltitlehomescreen;
cui_labeltitlehomescreen = lv_label_create(comp_parent);
lv_obj_set_width( cui_labeltitlehomescreen, lv_pct(100));
lv_obj_set_height( cui_labeltitlehomescreen, lv_pct(15));
lv_obj_set_x( cui_labeltitlehomescreen, lv_pct(0) );
lv_obj_set_y( cui_labeltitlehomescreen, lv_pct(-43) );
lv_obj_set_align( cui_labeltitlehomescreen, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_labeltitlehomescreen,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_labeltitlehomescreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(cui_labeltitlehomescreen,"Smart Box");
lv_obj_set_style_text_align(cui_labeltitlehomescreen, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_labeltitlehomescreen, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_labeltitlehomescreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_green);
ui_object_set_themeable_style_property(cui_labeltitlehomescreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_green);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELTITLEHOMESCREEN_NUM);
children[UI_COMP_LABELTITLEHOMESCREEN_LABELTITLEHOMESCREEN] = cui_labeltitlehomescreen;
lv_obj_add_event_cb(cui_labeltitlehomescreen, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_labeltitlehomescreen, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_labeltitlehomescreen_create_hook(cui_labeltitlehomescreen);
return cui_labeltitlehomescreen; 
}

