// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "../ui.h"


// COMPONENT containerColorBannerBottom1

lv_obj_t *ui_containercolorbannerbottom1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_containercolorbannerbottom1;
cui_containercolorbannerbottom1 = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_containercolorbannerbottom1);
lv_obj_set_width( cui_containercolorbannerbottom1, lv_pct(100));
lv_obj_set_height( cui_containercolorbannerbottom1, lv_pct(15));
lv_obj_set_x( cui_containercolorbannerbottom1, lv_pct(0) );
lv_obj_set_y( cui_containercolorbannerbottom1, lv_pct(43) );
lv_obj_set_align( cui_containercolorbannerbottom1, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_containercolorbannerbottom1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_containercolorbannerbottom1, lv_color_hex(0x272424), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_containercolorbannerbottom1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(cui_containercolorbannerbottom1, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERCOLORBANNERBOTTOM1_NUM);
children[UI_COMP_CONTAINERCOLORBANNERBOTTOM1_CONTAINERCOLORBANNERBOTTOM1] = cui_containercolorbannerbottom1;
lv_obj_add_event_cb(cui_containercolorbannerbottom1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_containercolorbannerbottom1, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_containercolorbannerbottom1_create_hook(cui_containercolorbannerbottom1);
return cui_containercolorbannerbottom1; 
}

