// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#ifndef _UI_COMP_LABELTITLEHOMESCREEN_H
#define _UI_COMP_LABELTITLEHOMESCREEN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT labelTitleHomeScreen
#define UI_COMP_LABELTITLEHOMESCREEN_LABELTITLEHOMESCREEN 0
#define _UI_COMP_LABELTITLEHOMESCREEN_NUM 1
lv_obj_t *ui_labeltitlehomescreen_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
