// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screenhome
void ui_screenhome_screen_init(void);
lv_obj_t *ui_screenhome;
lv_obj_t *ui_labeltitlehomescreen;
lv_obj_t *ui_containercolorbarhome;
lv_obj_t *ui_barroomclimate;
void ui_event_buttonoptions( lv_event_t * e);
lv_obj_t *ui_buttonoptions;
lv_obj_t *ui_imgindoor;
lv_obj_t *ui_imghumidty;
lv_obj_t *ui_imgoutdoor;
lv_obj_t *ui_labelindoor;
lv_obj_t *ui_labelhumidty;
lv_obj_t *ui_labeloutdoor;
lv_obj_t *ui_labeldatetime;
lv_obj_t *ui_imgconnected;
lv_obj_t *ui_containercolorbannerbottom;
// CUSTOM VARIABLES


// SCREEN: ui_screenoptions
void ui_screenoptions_screen_init(void);
lv_obj_t *ui_screenoptions;
lv_obj_t *ui_labeltitleoptions;
lv_obj_t *ui_containercolorbaroptions;
void ui_event_buttonexitfromoptions( lv_event_t * e);
lv_obj_t *ui_buttonexitfromoptions;
lv_obj_t *ui_buttonrooms;
lv_obj_t *ui_buttonoutdoorsensor;
lv_obj_t *ui_buttonwifi;
lv_obj_t *ui_buttonlanguage;
lv_obj_t *ui_buttonfurtheroptions;
lv_obj_t *ui_buttonsensoractivity;
void ui_event_buttonpin( lv_event_t * e);
lv_obj_t *ui_buttonpin;
// CUSTOM VARIABLES


// SCREEN: ui_screenpin
void ui_screenpin_screen_init(void);
lv_obj_t *ui_screenpin;
lv_obj_t *ui_labeltitleoptions1;
lv_obj_t *ui_containercolorbarpin;
lv_obj_t *ui_textareapin;
lv_obj_t *ui_keyboard1;
void ui_event_buttonexitfrompin( lv_event_t * e);
lv_obj_t *ui_buttonexitfrompin;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_signal[6] = {&ui_img_signal0_png, &ui_img_signal1_png, &ui_img_signal2_png, &ui_img_signal3_png, &ui_img_signal4_png, &ui_img_signal5_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_buttonoptions( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenoptions, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenoptions_screen_init);
}
}

void ui_event_buttonexitfromoptions( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenhome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenhome_screen_init);
}
}

void ui_event_buttonpin( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenpin, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenpin_screen_init);
}
}

void ui_event_buttonexitfrompin( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenoptions, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenoptions_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screenhome_screen_init();
ui_screenoptions_screen_init();
ui_screenpin_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screenhome);
}
