// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screenhome
void ui_screenhome_screen_init(void);
void ui_event_screenhome( lv_event_t * e);
lv_obj_t *ui_screenhome;
lv_obj_t *ui_containertopbarhome;
lv_obj_t *ui_labeltoptexthome;
lv_obj_t *ui_barroomclimate;
lv_obj_t *ui_imgindoor;
lv_obj_t *ui_imghumidty;
lv_obj_t *ui_imgoutdoor;
lv_obj_t *ui_labelindoor;
lv_obj_t *ui_labelhumidty;
lv_obj_t *ui_labeloutdoor;
lv_obj_t *ui_containerbottombarhome;
lv_obj_t *ui_imgconnected;
lv_obj_t *ui_labeldatetime;
void ui_event_buttonoptions( lv_event_t * e);
lv_obj_t *ui_buttonoptions;
// CUSTOM VARIABLES


// SCREEN: ui_screenhomeairpressure
void ui_screenhomeairpressure_screen_init(void);
void ui_event_screenhomeairpressure( lv_event_t * e);
lv_obj_t *ui_screenhomeairpressure;
lv_obj_t *ui_containertopbarairpressure;
lv_obj_t *ui_labeltoptexthome1;
lv_obj_t *ui_labelairpressuretext;
lv_obj_t *ui_containervalueairpressure;
lv_obj_t *ui_labelairpressure;
lv_obj_t *ui_labelunit;
lv_obj_t *ui_containerbottombarairpressure;
lv_obj_t *ui_imgconnected1;
lv_obj_t *ui_labeldatetime1;
void ui_event_buttonoptions1( lv_event_t * e);
lv_obj_t *ui_buttonoptions1;
// CUSTOM VARIABLES


// SCREEN: ui_screenhomeco2
void ui_screenhomeco2_screen_init(void);
void ui_event_screenhomeco2( lv_event_t * e);
lv_obj_t *ui_screenhomeco2;
lv_obj_t *ui_containertopbarco2;
lv_obj_t *ui_labeltoptexthome2;
lv_obj_t *ui_containertextco2;
lv_obj_t *ui_labelco2letters;
lv_obj_t *ui_labelco2number;
lv_obj_t *ui_containervalueco2;
lv_obj_t *ui_labelco2eval;
lv_obj_t *ui_labelco2value;
lv_obj_t *ui_labelco2unit;
lv_obj_t *ui_containerbottombarco2;
lv_obj_t *ui_imgconnected2;
lv_obj_t *ui_labeldatetime2;
void ui_event_buttonoptions2( lv_event_t * e);
lv_obj_t *ui_buttonoptions2;
// CUSTOM VARIABLES


// SCREEN: ui_screenoptions
void ui_screenoptions_screen_init(void);
lv_obj_t *ui_screenoptions;
lv_obj_t *ui_containercolorbaroptions;
void ui_event_buttonexitfromoptions( lv_event_t * e);
lv_obj_t *ui_buttonexitfromoptions;
lv_obj_t *ui_labeltitleoptions;
void ui_event_buttonpin( lv_event_t * e);
lv_obj_t *ui_buttonpin;
lv_obj_t *ui_container4;
lv_obj_t *ui_buttonrooms;
lv_obj_t *ui_buttonoutdoorsensor;
lv_obj_t *ui_buttonwifi;
lv_obj_t *ui_buttonlanguage;
lv_obj_t *ui_buttonsensoractivity;
lv_obj_t *ui_buttonfurtheroptions;
// CUSTOM VARIABLES


// SCREEN: ui_screenpin
void ui_screenpin_screen_init(void);
lv_obj_t *ui_screenpin;
lv_obj_t *ui_labeltitleoptions1;
lv_obj_t *ui_containercolorbarpin;
lv_obj_t *ui_textareapin;
lv_obj_t *ui_keyboard1;
void ui_event_buttonexitfrompin( lv_event_t * e);
lv_obj_t *ui_buttonexitfrompin;
// CUSTOM VARIABLES


// SCREEN: ui_screenrooms
void ui_screenrooms_screen_init(void);
lv_obj_t *ui_screenrooms;
lv_obj_t *ui_labeltitleoptions2;
lv_obj_t *ui_containercolorbaroptions1;
// CUSTOM VARIABLES


// SCREEN: ui_screenoutdoorsensor
void ui_screenoutdoorsensor_screen_init(void);
lv_obj_t *ui_screenoutdoorsensor;
lv_obj_t *ui_containercolorbaroptions2;
// CUSTOM VARIABLES


// SCREEN: ui_screenwlan
void ui_screenwlan_screen_init(void);
lv_obj_t *ui_screenwlan;
lv_obj_t *ui_containercolorbaroptions3;
lv_obj_t *ui_containercolorbaroptions4;
// CUSTOM VARIABLES


// SCREEN: ui_screenlanguage
void ui_screenlanguage_screen_init(void);
lv_obj_t *ui_screenlanguage;
lv_obj_t *ui_containercolorbaroptions5;
// CUSTOM VARIABLES


// SCREEN: ui_screenfurtheroptions
void ui_screenfurtheroptions_screen_init(void);
lv_obj_t *ui_screenfurtheroptions;
lv_obj_t *ui_containercolorbaroptions6;
// CUSTOM VARIABLES


// SCREEN: ui_screensensoractivity
void ui_screensensoractivity_screen_init(void);
lv_obj_t *ui_screensensoractivity;
lv_obj_t *ui_containercolorbaroptions7;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_signal[6] = {&ui_img_icons_signal0_png, &ui_img_icons_signal1_png, &ui_img_icons_signal2_png, &ui_img_icons_signal3_png, &ui_img_icons_signal4_png, &ui_img_icons_signal5_png};
const lv_img_dsc_t *ui_imgset_settings_x[1] = {&ui_img_icons_settings_50x50_png};
const lv_img_dsc_t *ui_imgset_connected_x[1] = {&ui_img_icons_connected_35x35_png};
const lv_img_dsc_t *ui_imgset_indoor_57x[1] = {&ui_img_icons_indoor_57x108_png};
const lv_img_dsc_t *ui_imgset_humidity_72x[1] = {&ui_img_icons_humidity_72x108_png};
const lv_img_dsc_t *ui_imgset_outdoor_x[1] = {&ui_img_icons_outdoor_108x108_png};
const lv_img_dsc_t *ui_imgset_rooms_84x[1] = {&ui_img_icons_rooms_84x72_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_screenhome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenhomeairpressure, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_screenhomeairpressure_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenhomeco2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_screenhomeco2_screen_init);
}
}

void ui_event_buttonoptions( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenoptions, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenoptions_screen_init);
}
}

void ui_event_screenhomeairpressure( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenhomeco2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_screenhomeco2_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenhome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_screenhome_screen_init);
}
}

void ui_event_buttonoptions1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenoptions, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenoptions_screen_init);
}
}

void ui_event_screenhomeco2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenhome, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_screenhome_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screenhomeairpressure, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_screenhomeairpressure_screen_init);
}
}

void ui_event_buttonoptions2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenoptions, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenoptions_screen_init);
}
}

void ui_event_buttonexitfromoptions( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenhome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenhome_screen_init);
}
}

void ui_event_buttonpin( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenpin, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenpin_screen_init);
}
}

void ui_event_buttonexitfrompin( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenoptions, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screenoptions_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screenhome_screen_init();
ui_screenhomeairpressure_screen_init();
ui_screenhomeco2_screen_init();
ui_screenoptions_screen_init();
ui_screenpin_screen_init();
ui_screenrooms_screen_init();
ui_screenoutdoorsensor_screen_init();
ui_screenwlan_screen_init();
ui_screenlanguage_screen_init();
ui_screenfurtheroptions_screen_init();
ui_screensensoractivity_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screenhome);
}
