// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#ifndef _HSB_INDICATOR_UI_H
#define _HSB_INDICATOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

    #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_screenhome
void ui_screenhome_screen_init(void);
void ui_event_screenhome( lv_event_t * e);
extern lv_obj_t *ui_screenhome;
extern lv_obj_t *ui_labeltitlehomescreen;
extern lv_obj_t *ui_containercolorbarhome;
extern lv_obj_t *ui_barroomclimate;
void ui_event_buttonoptions( lv_event_t * e);
extern lv_obj_t *ui_buttonoptions;
extern lv_obj_t *ui_imgindoor;
extern lv_obj_t *ui_imghumidty;
extern lv_obj_t *ui_imgoutdoor;
extern lv_obj_t *ui_labelindoor;
extern lv_obj_t *ui_labelhumidty;
extern lv_obj_t *ui_labeloutdoor;
extern lv_obj_t *ui_labeldatetime;
extern lv_obj_t *ui_imgconnected;
extern lv_obj_t *ui_containercolorbannerbottom;
// CUSTOM VARIABLES

// SCREEN: ui_screenhomeairpressure
void ui_screenhomeairpressure_screen_init(void);
void ui_event_screenhomeairpressure( lv_event_t * e);
extern lv_obj_t *ui_screenhomeairpressure;
extern lv_obj_t *ui_labeltitlehomescreen1;
extern lv_obj_t *ui_containercolorbarhome1;
extern lv_obj_t *ui_containercolorbannerbottom1;
extern lv_obj_t *ui_labelairpressuretext;
extern lv_obj_t *ui_labelairpressurevalue;
extern lv_obj_t *ui_imgconnected1;
extern lv_obj_t *ui_labeldatetime1;
void ui_event_buttonoptions1( lv_event_t * e);
extern lv_obj_t *ui_buttonoptions1;
// CUSTOM VARIABLES

// SCREEN: ui_screenhomeco2
void ui_screenhomeco2_screen_init(void);
void ui_event_screenhomeco2( lv_event_t * e);
extern lv_obj_t *ui_screenhomeco2;
extern lv_obj_t *ui_labeltitlehomescreen2;
extern lv_obj_t *ui_containercolorbarhome2;
extern lv_obj_t *ui_barroomclimate1;
extern lv_obj_t *ui_containercolorbannerbottom2;
extern lv_obj_t *ui_labelco2leveltext;
extern lv_obj_t *ui_labelco2levelvalue;
extern lv_obj_t *ui_imgconnected2;
extern lv_obj_t *ui_labeldatetime2;
void ui_event_buttonoptions2( lv_event_t * e);
extern lv_obj_t *ui_buttonoptions2;
extern lv_obj_t *ui_label3;
// CUSTOM VARIABLES

// SCREEN: ui_screenoptions
void ui_screenoptions_screen_init(void);
extern lv_obj_t *ui_screenoptions;
extern lv_obj_t *ui_labeltitleoptions;
extern lv_obj_t *ui_containercolorbaroptions;
void ui_event_buttonexitfromoptions( lv_event_t * e);
extern lv_obj_t *ui_buttonexitfromoptions;
extern lv_obj_t *ui_buttonrooms;
extern lv_obj_t *ui_buttonoutdoorsensor;
extern lv_obj_t *ui_buttonwifi;
extern lv_obj_t *ui_buttonlanguage;
extern lv_obj_t *ui_buttonfurtheroptions;
extern lv_obj_t *ui_buttonsensoractivity;
void ui_event_buttonpin( lv_event_t * e);
extern lv_obj_t *ui_buttonpin;
// CUSTOM VARIABLES

// SCREEN: ui_screenpin
void ui_screenpin_screen_init(void);
extern lv_obj_t *ui_screenpin;
extern lv_obj_t *ui_labeltitleoptions1;
extern lv_obj_t *ui_containercolorbarpin;
extern lv_obj_t *ui_textareapin;
extern lv_obj_t *ui_keyboard1;
void ui_event_buttonexitfrompin( lv_event_t * e);
extern lv_obj_t *ui_buttonexitfrompin;
// CUSTOM VARIABLES

// SCREEN: ui_screenrooms
void ui_screenrooms_screen_init(void);
extern lv_obj_t *ui_screenrooms;
extern lv_obj_t *ui_labeltitleoptions2;
extern lv_obj_t *ui_containercolorbaroptions1;
// CUSTOM VARIABLES

// SCREEN: ui_screenoutdoorsensor
void ui_screenoutdoorsensor_screen_init(void);
extern lv_obj_t *ui_screenoutdoorsensor;
extern lv_obj_t *ui_containercolorbaroptions2;
// CUSTOM VARIABLES

// SCREEN: ui_screenwlan
void ui_screenwlan_screen_init(void);
extern lv_obj_t *ui_screenwlan;
extern lv_obj_t *ui_containercolorbaroptions3;
extern lv_obj_t *ui_containercolorbaroptions4;
// CUSTOM VARIABLES

// SCREEN: ui_screenlanguage
void ui_screenlanguage_screen_init(void);
extern lv_obj_t *ui_screenlanguage;
extern lv_obj_t *ui_containercolorbaroptions5;
// CUSTOM VARIABLES

// SCREEN: ui_screenfurtheroptions
void ui_screenfurtheroptions_screen_init(void);
extern lv_obj_t *ui_screenfurtheroptions;
extern lv_obj_t *ui_containercolorbaroptions6;
// CUSTOM VARIABLES

// SCREEN: ui_screensensoractivity
void ui_screensensoractivity_screen_init(void);
extern lv_obj_t *ui_screensensoractivity;
extern lv_obj_t *ui_containercolorbaroptions7;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_icons_settings_png);   // assets/icons/settings.png
LV_IMG_DECLARE( ui_img_icons_indoor_png);   // assets/icons/indoor.png
LV_IMG_DECLARE( ui_img_icons_humidity_png);   // assets/icons/humidity.png
LV_IMG_DECLARE( ui_img_icons_outdoor_png);   // assets/icons/outdoor.png
LV_IMG_DECLARE( ui_img_icons_connected_png);   // assets/icons/connected.png
LV_IMG_DECLARE( ui_img_icons_arrow_left_white_png);   // assets/icons/arrow_left_white.png
LV_IMG_DECLARE( ui_img_icons_rooms_png);   // assets/icons/rooms.png
LV_IMG_DECLARE( ui_img_icons_outdoor_white_png);   // assets/icons/outdoor_white.png
LV_IMG_DECLARE( ui_img_icons_wifi_icon_small_png);   // assets/icons/wifi_icon_small.png
LV_IMG_DECLARE( ui_img_icons_language_png);   // assets/icons/language.png
LV_IMG_DECLARE( ui_img_icons_options_png);   // assets/icons/options.png
LV_IMG_DECLARE( ui_img_icons_list_icon_png);   // assets/icons/list_icon.png
LV_IMG_DECLARE( ui_img_icons_key_icon_small_png);   // assets/icons/key_icon_small.png
LV_IMG_DECLARE( ui_img_icons_signal0_png);   // assets/icons/signal0.png
LV_IMG_DECLARE( ui_img_icons_signal1_png);   // assets/icons/signal1.png
LV_IMG_DECLARE( ui_img_icons_signal2_png);   // assets/icons/signal2.png
LV_IMG_DECLARE( ui_img_icons_signal3_png);   // assets/icons/signal3.png
LV_IMG_DECLARE( ui_img_icons_signal4_png);   // assets/icons/signal4.png
LV_IMG_DECLARE( ui_img_icons_signal5_png);   // assets/icons/signal5.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
