// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_green[1] = {0x3BA80F};
const ui_theme_variable_t _ui_theme_alpha_green[1] = {255};

const ui_theme_variable_t _ui_theme_color_lightgrey[1] = {0xBBBBBB};
const ui_theme_variable_t _ui_theme_alpha_lightgrey[1] = {255};

const ui_theme_variable_t _ui_theme_color_white[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_white[1] = {255};

const ui_theme_variable_t _ui_theme_color_darkgrey[1] = {0x6A6A6A};
const ui_theme_variable_t _ui_theme_alpha_darkgrey[1] = {255};

const ui_theme_variable_t _ui_theme_color_grey[1] = {0x8F8F8F};
const ui_theme_variable_t _ui_theme_alpha_grey[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

