// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_GREEN 0
#define UI_THEME_COLOR_LIGHTGREY 1
#define UI_THEME_COLOR_WHITE 2
#define UI_THEME_COLOR_DARKGREY 3
#define UI_THEME_COLOR_GREY 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_green[1];
extern const ui_theme_variable_t _ui_theme_alpha_green[1];

extern const ui_theme_variable_t _ui_theme_color_lightgrey[1];
extern const ui_theme_variable_t _ui_theme_alpha_lightgrey[1];

extern const ui_theme_variable_t _ui_theme_color_white[1];
extern const ui_theme_variable_t _ui_theme_alpha_white[1];

extern const ui_theme_variable_t _ui_theme_color_darkgrey[1];
extern const ui_theme_variable_t _ui_theme_alpha_darkgrey[1];

extern const ui_theme_variable_t _ui_theme_color_grey[1];
extern const ui_theme_variable_t _ui_theme_alpha_grey[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
